# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DC-VFX_renderman_denoiser_v01.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 1038)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(400, 70))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(70, 70))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("images/images.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Denoise = QtWidgets.QWidget()
        self.Denoise.setObjectName("Denoise")
        self.select_btn = QtWidgets.QPushButton(self.Denoise)
        self.select_btn.setGeometry(QtCore.QRect(10, 30, 231, 23))
        self.select_btn.setObjectName("select_btn")
        self.label_2 = QtWidgets.QLabel(self.Denoise)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 161, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.Denoise)
        self.label.setGeometry(QtCore.QRect(180, 70, 531, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.Denoise)
        self.line.setGeometry(QtCore.QRect(10, 80, 1061, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_create_new_sequence = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence.setEnabled(True)
        self.groupBox_create_new_sequence.setGeometry(QtCore.QRect(11, 100, 1061, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence.setObjectName("groupBox_create_new_sequence")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_sequence_btn = QtWidgets.QPushButton(self.groupBox_create_new_sequence)
        self.create_sequence_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/gpu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn.setIcon(icon)
        self.create_sequence_btn.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn.setObjectName("create_sequence_btn")
        self.horizontalLayout.addWidget(self.create_sequence_btn)
        self.radioButton_jpg = QtWidgets.QRadioButton(self.groupBox_create_new_sequence)
        self.radioButton_jpg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_jpg.setObjectName("radioButton_jpg")
        self.horizontalLayout.addWidget(self.radioButton_jpg)
        self.radioButton_png = QtWidgets.QRadioButton(self.groupBox_create_new_sequence)
        self.radioButton_png.setObjectName("radioButton_png")
        self.horizontalLayout.addWidget(self.radioButton_png)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.groupBox_create_new_sequence_2 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence_2.setEnabled(True)
        self.groupBox_create_new_sequence_2.setGeometry(QtCore.QRect(10, 180, 471, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence_2.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence_2.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence_2.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence_2.setObjectName("groupBox_create_new_sequence_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_sequence_btn_2 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_2)
        self.create_sequence_btn_2.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_2.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/skip_first.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn_2.setIcon(icon1)
        self.create_sequence_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn_2.setObjectName("create_sequence_btn_2")
        self.horizontalLayout_3.addWidget(self.create_sequence_btn_2)
        self.radioButton_jpg_2 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_2)
        self.radioButton_jpg_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_jpg_2.setObjectName("radioButton_jpg_2")
        self.horizontalLayout_3.addWidget(self.radioButton_jpg_2)
        self.radioButton_png_2 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_2)
        self.radioButton_png_2.setObjectName("radioButton_png_2")
        self.horizontalLayout_3.addWidget(self.radioButton_png_2)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_16)
        self.groupBox_create_new_sequence_3 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence_3.setEnabled(True)
        self.groupBox_create_new_sequence_3.setGeometry(QtCore.QRect(490, 180, 581, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence_3.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence_3.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence_3.setObjectName("groupBox_create_new_sequence_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.create_sequence_btn_3 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_3)
        self.create_sequence_btn_3.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_3.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/skip_last.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn_3.setIcon(icon2)
        self.create_sequence_btn_3.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn_3.setObjectName("create_sequence_btn_3")
        self.horizontalLayout_5.addWidget(self.create_sequence_btn_3)
        self.radioButton_jpg_3 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_3)
        self.radioButton_jpg_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_jpg_3.setObjectName("radioButton_jpg_3")
        self.horizontalLayout_5.addWidget(self.radioButton_jpg_3)
        self.radioButton_png_3 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_3)
        self.radioButton_png_3.setObjectName("radioButton_png_3")
        self.horizontalLayout_5.addWidget(self.radioButton_png_3)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.groupBox_create_new_sequence_4 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence_4.setEnabled(True)
        self.groupBox_create_new_sequence_4.setGeometry(QtCore.QRect(11, 260, 1061, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence_4.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence_4.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence_4.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence_4.setObjectName("groupBox_create_new_sequence_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence_4)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.create_sequence_btn_4 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_4)
        self.create_sequence_btn_4.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_4.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/suffix.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn_4.setIcon(icon3)
        self.create_sequence_btn_4.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn_4.setObjectName("create_sequence_btn_4")
        self.horizontalLayout_21.addWidget(self.create_sequence_btn_4)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_create_new_sequence_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(400, 20))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_21.addWidget(self.textEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.groupBox_create_new_sequence_5 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence_5.setEnabled(True)
        self.groupBox_create_new_sequence_5.setGeometry(QtCore.QRect(11, 340, 1061, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence_5.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence_5.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence_5.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence_5.setObjectName("groupBox_create_new_sequence_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence_5)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.create_sequence_btn_5 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_5)
        self.create_sequence_btn_5.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_5.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn_5.setIcon(icon4)
        self.create_sequence_btn_5.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn_5.setObjectName("create_sequence_btn_5")
        self.horizontalLayout_24.addWidget(self.create_sequence_btn_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_24.addWidget(self.pushButton_5)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.groupBox_create_new_sequence_6 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_create_new_sequence_6.setEnabled(True)
        self.groupBox_create_new_sequence_6.setGeometry(QtCore.QRect(11, 420, 1061, 82))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_create_new_sequence_6.sizePolicy().hasHeightForWidth())
        self.groupBox_create_new_sequence_6.setSizePolicy(sizePolicy)
        self.groupBox_create_new_sequence_6.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_create_new_sequence_6.setObjectName("groupBox_create_new_sequence_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_create_new_sequence_6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.create_sequence_btn_6 = QtWidgets.QPushButton(self.groupBox_create_new_sequence_6)
        self.create_sequence_btn_6.setMinimumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_6.setMaximumSize(QtCore.QSize(45, 45))
        self.create_sequence_btn_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/cross-frame.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_sequence_btn_6.setIcon(icon5)
        self.create_sequence_btn_6.setIconSize(QtCore.QSize(30, 30))
        self.create_sequence_btn_6.setObjectName("create_sequence_btn_6")
        self.horizontalLayout_27.addWidget(self.create_sequence_btn_6)
        self.radioButton_jpg_4 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_6)
        self.radioButton_jpg_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_jpg_4.setObjectName("radioButton_jpg_4")
        self.horizontalLayout_27.addWidget(self.radioButton_jpg_4)
        self.radioButton_png_4 = QtWidgets.QRadioButton(self.groupBox_create_new_sequence_6)
        self.radioButton_png_4.setObjectName("radioButton_png_4")
        self.horizontalLayout_27.addWidget(self.radioButton_png_4)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 500, 1061, 80))
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/filter-type.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_28.addWidget(self.pushButton_6)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(160, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_29.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_29.addWidget(self.comboBox_2)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_29)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 580, 1061, 80))
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_7.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/pre-filters.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_30.addWidget(self.pushButton_7)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(160, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_31.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_31.addWidget(self.comboBox_3)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.groupBox_6 = QtWidgets.QGroupBox(self.Denoise)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 660, 1061, 80))
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_8.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_8.setMaximumSize(QtCore.QSize(45, 45))
        self.pushButton_8.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/threads.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_32.addWidget(self.pushButton_8)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(160, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_33.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(120, "")
        self.horizontalLayout_33.addWidget(self.comboBox_4)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_33)
        self.select_btn_2 = QtWidgets.QPushButton(self.Denoise)
        self.select_btn_2.setGeometry(QtCore.QRect(10, 760, 229, 23))
        self.select_btn_2.setObjectName("select_btn_2")
        self.tabWidget.addTab(self.Denoise, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 150, 13))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 541, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(630, 40, 261, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 90, 541, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 120, 541, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 150, 541, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 180, 541, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 210, 541, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 240, 541, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 270, 541, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 300, 541, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 180, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(150, 0))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(150, 0))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(20, 240, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(150, 0))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(20, 270, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(150, 0))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 300, 150, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(150, 0))
        self.label_16.setObjectName("label_16")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(630, 60, 82, 17))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(630, 90, 82, 17))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(630, 120, 82, 17))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(630, 150, 82, 17))
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(630, 180, 82, 17))
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(630, 210, 82, 17))
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(630, 240, 82, 17))
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_8.setGeometry(QtCore.QRect(630, 270, 82, 17))
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_9.setGeometry(QtCore.QRect(630, 300, 82, 17))
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_btn.setText(_translate("MainWindow", "Select your render..."))
        self.label_2.setText(_translate("MainWindow", "Your selected render sequence is:"))
        self.label.setText(_translate("MainWindow", "..."))
        self.groupBox_create_new_sequence.setTitle(_translate("MainWindow", "Utilize GPU"))
        self.radioButton_jpg.setText(_translate("MainWindow", "Yes"))
        self.radioButton_png.setText(_translate("MainWindow", "No"))
        self.groupBox_create_new_sequence_2.setTitle(_translate("MainWindow", "Skip first frame?"))
        self.radioButton_jpg_2.setText(_translate("MainWindow", "Yes"))
        self.radioButton_png_2.setText(_translate("MainWindow", "No"))
        self.groupBox_create_new_sequence_3.setTitle(_translate("MainWindow", "Skip last frame?"))
        self.radioButton_jpg_3.setText(_translate("MainWindow", "Yes"))
        self.radioButton_png_3.setText(_translate("MainWindow", "No"))
        self.groupBox_create_new_sequence_4.setTitle(_translate("MainWindow", "Desired output suffix (leave blank for default \'filename + filtered.exr\')"))
        self.groupBox_create_new_sequence_5.setTitle(_translate("MainWindow", "Desired output folder (leave blank for the same folder as your input data)"))
        self.pushButton_5.setText(_translate("MainWindow", "Select a directory..."))
        self.groupBox_create_new_sequence_6.setTitle(_translate("MainWindow", "Cross-frame filter mode"))
        self.radioButton_jpg_4.setText(_translate("MainWindow", "Yes"))
        self.radioButton_png_4.setText(_translate("MainWindow", "No"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Filter type"))
        self.label_6.setText(_translate("MainWindow", "Select your desired filter type"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "default"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "sigmaAlphaOnly"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "volume"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Optional premade filters"))
        self.label_7.setText(_translate("MainWindow", "optional pre-made Filters"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "fireflyKiller.filteroverride.json"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "linearWarp.filteroverride.json"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "nearestWarp.filteroverride.json"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "noAlbedoDivide.filteroverride.json"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "noDepth.filteroverride.json"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "noFireflyKiller.filteroverride.json"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "nonsplitVariances.filteroverride.json"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "noUnpremultiplyColor.filteroverride.json"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "splitVariances.filteroverride.json"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "unpremultiplyColor.filteroverride.json"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "unpremultiplyFeatures.filteroverride.json"))
        self.groupBox_6.setTitle(_translate("MainWindow", "How many threads"))
        self.label_8.setText(_translate("MainWindow", "Select your desired thread count"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_4.setItemText(49, _translate("MainWindow", "50"))
        self.comboBox_4.setItemText(50, _translate("MainWindow", "51"))
        self.comboBox_4.setItemText(51, _translate("MainWindow", "52"))
        self.comboBox_4.setItemText(52, _translate("MainWindow", "53"))
        self.comboBox_4.setItemText(53, _translate("MainWindow", "54"))
        self.comboBox_4.setItemText(54, _translate("MainWindow", "55"))
        self.comboBox_4.setItemText(55, _translate("MainWindow", "56"))
        self.comboBox_4.setItemText(56, _translate("MainWindow", "57"))
        self.comboBox_4.setItemText(57, _translate("MainWindow", "58"))
        self.comboBox_4.setItemText(58, _translate("MainWindow", "59"))
        self.comboBox_4.setItemText(59, _translate("MainWindow", "60"))
        self.comboBox_4.setItemText(60, _translate("MainWindow", "61"))
        self.comboBox_4.setItemText(61, _translate("MainWindow", "62"))
        self.comboBox_4.setItemText(62, _translate("MainWindow", "63"))
        self.comboBox_4.setItemText(63, _translate("MainWindow", "64"))
        self.comboBox_4.setItemText(64, _translate("MainWindow", "65"))
        self.comboBox_4.setItemText(65, _translate("MainWindow", "66"))
        self.comboBox_4.setItemText(66, _translate("MainWindow", "67"))
        self.comboBox_4.setItemText(67, _translate("MainWindow", "68"))
        self.comboBox_4.setItemText(68, _translate("MainWindow", "69"))
        self.comboBox_4.setItemText(69, _translate("MainWindow", "70"))
        self.comboBox_4.setItemText(70, _translate("MainWindow", "71"))
        self.comboBox_4.setItemText(71, _translate("MainWindow", "72"))
        self.comboBox_4.setItemText(72, _translate("MainWindow", "73"))
        self.comboBox_4.setItemText(73, _translate("MainWindow", "74"))
        self.comboBox_4.setItemText(74, _translate("MainWindow", "75"))
        self.comboBox_4.setItemText(75, _translate("MainWindow", "76"))
        self.comboBox_4.setItemText(76, _translate("MainWindow", "77"))
        self.comboBox_4.setItemText(77, _translate("MainWindow", "78"))
        self.comboBox_4.setItemText(78, _translate("MainWindow", "79"))
        self.comboBox_4.setItemText(79, _translate("MainWindow", "80"))
        self.comboBox_4.setItemText(80, _translate("MainWindow", "81"))
        self.comboBox_4.setItemText(81, _translate("MainWindow", "82"))
        self.comboBox_4.setItemText(82, _translate("MainWindow", "83"))
        self.comboBox_4.setItemText(83, _translate("MainWindow", "84"))
        self.comboBox_4.setItemText(84, _translate("MainWindow", "85"))
        self.comboBox_4.setItemText(85, _translate("MainWindow", "86"))
        self.comboBox_4.setItemText(86, _translate("MainWindow", "87"))
        self.comboBox_4.setItemText(87, _translate("MainWindow", "88"))
        self.comboBox_4.setItemText(88, _translate("MainWindow", "89"))
        self.comboBox_4.setItemText(89, _translate("MainWindow", "90"))
        self.comboBox_4.setItemText(90, _translate("MainWindow", "91"))
        self.comboBox_4.setItemText(91, _translate("MainWindow", "92"))
        self.comboBox_4.setItemText(92, _translate("MainWindow", "93"))
        self.comboBox_4.setItemText(93, _translate("MainWindow", "94"))
        self.comboBox_4.setItemText(94, _translate("MainWindow", "95"))
        self.comboBox_4.setItemText(95, _translate("MainWindow", "96"))
        self.comboBox_4.setItemText(96, _translate("MainWindow", "97"))
        self.comboBox_4.setItemText(97, _translate("MainWindow", "98"))
        self.comboBox_4.setItemText(98, _translate("MainWindow", "99"))
        self.comboBox_4.setItemText(99, _translate("MainWindow", "100"))
        self.comboBox_4.setItemText(100, _translate("MainWindow", "101"))
        self.comboBox_4.setItemText(101, _translate("MainWindow", "102"))
        self.comboBox_4.setItemText(102, _translate("MainWindow", "103"))
        self.comboBox_4.setItemText(103, _translate("MainWindow", "104"))
        self.comboBox_4.setItemText(104, _translate("MainWindow", "105"))
        self.comboBox_4.setItemText(105, _translate("MainWindow", "106"))
        self.comboBox_4.setItemText(106, _translate("MainWindow", "107"))
        self.comboBox_4.setItemText(107, _translate("MainWindow", "108"))
        self.comboBox_4.setItemText(108, _translate("MainWindow", "109"))
        self.comboBox_4.setItemText(109, _translate("MainWindow", "110"))
        self.comboBox_4.setItemText(110, _translate("MainWindow", "111"))
        self.comboBox_4.setItemText(111, _translate("MainWindow", "112"))
        self.comboBox_4.setItemText(112, _translate("MainWindow", "113"))
        self.comboBox_4.setItemText(113, _translate("MainWindow", "114"))
        self.comboBox_4.setItemText(114, _translate("MainWindow", "115"))
        self.comboBox_4.setItemText(115, _translate("MainWindow", "116"))
        self.comboBox_4.setItemText(116, _translate("MainWindow", "117"))
        self.comboBox_4.setItemText(117, _translate("MainWindow", "118"))
        self.comboBox_4.setItemText(118, _translate("MainWindow", "119"))
        self.comboBox_4.setItemText(119, _translate("MainWindow", "120"))
        self.select_btn_2.setText(_translate("MainWindow", "DENOISE YOUR RENDER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Denoise), _translate("MainWindow", "Denoise"))
        self.label_3.setText(_translate("MainWindow", "Your denoiser.exe folder(s)"))
        self.label_4.setText(_translate("MainWindow", "Select your preferred version to use:"))
        self.label_5.setText(_translate("MainWindow", "V1"))
        self.label_9.setText(_translate("MainWindow", "V2"))
        self.label_10.setText(_translate("MainWindow", "V3"))
        self.label_11.setText(_translate("MainWindow", "V4"))
        self.label_12.setText(_translate("MainWindow", "V5"))
        self.label_13.setText(_translate("MainWindow", "V6"))
        self.label_14.setText(_translate("MainWindow", "V7"))
        self.label_15.setText(_translate("MainWindow", "V8"))
        self.label_16.setText(_translate("MainWindow", "V9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
